# More info on config here: https://github.com/golangci/golangci-lint#config-file
run:
  deadline: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  goimports:
    local-prefixes: github.com/kkuprikov/easy-go
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  dupl:
    threshold: 100
  goconst:
    min-len:         2
    min-occurrences: 2

linters:
  enable-all: true

issues:
  exclude-use-default: false
