version: "3.2"

networks:
  proxy:
    external: false

services:
  haproxy:
    image: haproxy:latest
    depends_on:
      - wsgatherer
    volumes:
      - "~/easy-go/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
    ports:
      - "80:5000"
      - "1936:1936"
    environment:
      LOG_LEVEL: "info"
    networks:
      - proxy

  redis:
    image: redis:5.0.5
    command: redis-server
    networks:
      - proxy

  wsgatherer:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./main
    networks:
      - proxy
    environment:
      - LOG_LEVEL=debug
      - WSGATHERER_PORT=1200
    ports:
      - "1200:1200"
      - "1201:1201"
      - "7000:7000"
      - "8080:8080"
    logging:
      driver: "json-file"
