name: Test
on: [push]
  branches:
  - master
  - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - uses: actions/checkout@v1

    - name: Build
      run: |
        go build -o /dev/null ./cmd/

  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1

    - name: Set up linter
      run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0

    - name: Lint
      run: |
        ./bin/golangci-lint run --enable-all ./...


